name = "SOLPS2IMAS"
uuid = "09becab6-0636-4c23-a92a-2b3723265c31"
authors = ["David Eldon <eldond@fusion.gat.com>"]
version = "1.0.3"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Fortran90Namelists = "8fb689aa-71ff-4044-8071-0cffc910b57d"
GGDUtils = "b7b5e640-9b39-4803-84eb-376048795def"
IMASdd = "c5a45a97-b3f9-491c-b9a7-aa88c3bc0067"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ArgParse = "1"
DelimitedFiles = "1.9.1"
Fortran90Namelists = "0.1"
GGDUtils = "1.0.2"
IMASdd = "2"
NCDatasets = "0.14.4"
Revise = "3.5.15"
YAML = "0.4.11"
julia = ">= 1.10"
